"use client";
import { useState } from "react";

import {
  BarChart3,
  TrendingUp,
  Briefcase,
  Globe,
  Zap,
  BookOpen,
  ArrowRight
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import LoginModal from "@/app/user/_components/LoginModal";
import RegisterModal from "@/app/user/_components/RegisterModal";
import { Button } from "@/shared-components/ui/button";
import { Card, CardContent } from "@/shared-components/ui/card";
import { Badge } from "@/shared-components/ui/badge";

/**
 * ServicesPage - Displays the premium stock market services offered by Praedico.
 */
export default function ServicesPage() {
  const services = [
    {
      title: "Stock Analysis",
      description: "In-depth technical and fundamental analysis of global equities using institutional-grade data and AI-driven insights.",
      icon: <BarChart3 className="w-8 h-8" />,
      color: "text-indigo-400",
      bg: "bg-indigo-500/10",
      hoverShadow: "shadow-indigo-500/20"
    },
    {
      title: "Investment Strategies",
      description: "Custom-tailored quantitative and qualitative strategies designed to maximize Alpha while strictly managing risk parameters.",
      icon: <TrendingUp className="w-8 h-8" />,
      color: "text-emerald-400",
      bg: "bg-emerald-500/10",
      hoverShadow: "shadow-emerald-500/20"
    },
    {
      title: "Portfolio Management",
      description: "Advanced asset allocation tools and professional management services to optimize your long-term wealth growth.",
      icon: <Briefcase className="w-8 h-8" />,
      color: "text-fuchsia-400",
      bg: "bg-fuchsia-500/10",
      hoverShadow: "shadow-fuchsia-500/20"
    },
    {
      title: "Live Market Updates",
      description: "Real-time streaming data and break-out alerts from global markets, ensuring you never miss a significant move.",
      icon: <Globe className="w-8 h-8" />,
      color: "text-blue-400",
      bg: "bg-blue-500/10",
      hoverShadow: "shadow-blue-500/20"
    },
    {
      title: "Trading Signals",
      description: "High-precision intra-day and swing trading signals generated by our proprietary algorithmic models.",
      icon: <Zap className="w-8 h-8" />,
      color: "text-orange-400",
      bg: "bg-orange-500/10",
      hoverShadow: "shadow-orange-500/20"
    },
    {
      title: "Market Education",
      description: "Comprehensive learning modules, webinars, and resources for investors of all levels to master the financial markets.",
      icon: <BookOpen className="w-8 h-8" />,
      color: "text-rose-400",
      bg: "bg-rose-500/10",
      hoverShadow: "shadow-rose-500/20"
    }
  ];
  
  const [isLoginModalOpen, setIsLoginModalOpen] = useState(false);
  const [isRegisterModalOpen, setIsRegisterModalOpen] = useState(false);

  return (
    <div className="min-h-screen bg-[#020617] text-white selection:bg-indigo-500/30 font-sans pb-20 pt-32 lg:pt-40">

      {/* 1. HERO SECTION (Standardized) */}
      <section className="container mx-auto px-6 mb-16 text-center">
        <div className="max-w-4xl mx-auto space-y-3">
          <p className="inline-flex">
            <Badge variant="outline" className="text-xs md:text-sm font-bold uppercase tracking-[0.5em] text-indigo-400 border-indigo-500/30 bg-indigo-500/5 px-4 py-1 animate-in fade-in slide-in-from-bottom-4 duration-700">
              Our Premium Services
            </Badge>
          </p>
          <h1 className="text-2xl md:text-3xl lg:text-5xl font-black tracking-tight leading-tight text-white animate-in fade-in slide-in-from-bottom-8 duration-1000 max-w-3xl mx-auto">
            Professional stock market tools and services to help you <span className="text-indigo-500">invest smarter.</span>
          </h1>
          <div className="pt-6">
            <div className="h-1 w-20 bg-indigo-600 mx-auto rounded-full shadow-[0_0_20px_rgba(79,70,229,0.5)]" />
          </div>
        </div>
      </section>

      {/* 2. SERVICES GRID */}
      <section className="container mx-auto px-6 mb-20">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-7xl mx-auto">
          {services.map((service, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1 }}
            >
              <Card
                className={`group relative p-8 rounded-3xl bg-[#020617]/40 border-white/5 overflow-hidden hover:border-white/20 transition-all duration-500 hover:-translate-y-2 hover:bg-slate-900/50 hover:shadow-2xl ${service.hoverShadow}`}
              >
                {/* Background Glow */}
                <div className={`absolute -inset-24 bg-gradient-to-br from-indigo-500/5 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-700 blur-[80px] pointer-events-none`} />

                <CardContent className="p-0 relative z-10 space-y-6">
                  <div className={`w-14 h-14 rounded-xl ${service.bg} ${service.color} flex items-center justify-center group-hover:scale-110 group-hover:rotate-6 transition-all duration-500`}>
                    {service.icon}
                  </div>

                  <div className="space-y-3">
                    <h3 className="text-xl font-bold tracking-tight text-white">{service.title}</h3>
                    <p className="text-slate-400 text-sm leading-relaxed font-medium">
                      {service.description}
                    </p>
                  </div>

                  <div className="pt-2 flex items-center gap-3">
                    <Button
                      variant="link"
                      onClick={() => setIsLoginModalOpen(true)}
                      className="h-auto p-0 flex items-center gap-2 text-[10px] font-bold text-indigo-400 group/link hover:text-indigo-300 transition-colors uppercase tracking-widest"
                    >
                      LEARN MORE
                      <ArrowRight className="w-3.5 h-3.5 group-hover/link:translate-x-1 transition-transform" />
                    </Button>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      </section>

      {/* AUTH MODALS */}
      <LoginModal
        isOpen={isLoginModalOpen}
        onClose={() => setIsLoginModalOpen(false)}
        onSwitchToRegister={() => {
          setIsLoginModalOpen(false);
          setIsRegisterModalOpen(true);
        }}
      />
      <RegisterModal
        isOpen={isRegisterModalOpen}
        onClose={() => setIsRegisterModalOpen(false)}
        onSwitchToLogin={() => {
          setIsRegisterModalOpen(false);
          setIsLoginModalOpen(true);
        }}
      />

    </div>
  );
}