/**
 * ─────────────────────────────────────────────────────
 *  CENTRALIZED PRICING CONFIG  ·  Frontend (Display)
 * ─────────────────────────────────────────────────────
 *  Amounts are in RUPEES (₹) for display only.
 *  The backend has its own copy in paise that it uses
 *  for the actual Razorpay charge.
 *
 *  To update prices: change values here (UI display)
 *  AND in backend/src/config/pricing.config.ts (charge).
 *  Keys: plan name → duration in months → rupees.
 * ─────────────────────────────────────────────────────
 */

export type PlanName = 'Silver' | 'Gold' | 'Diamond';
export type Duration = 1 | 3 | 6;

export const PLAN_PRICES: Record<PlanName, Record<Duration, number>> = {
  Silver:  { 1: 499,   3: 1299,  6: 2499  },
  Gold:    { 1: 999,   3: 2699,  6: 5199  },
  Diamond: { 1: 2499,  3: 6499,  6: 12499 },
};

/** Duration labels shown on the toggle */
export const DURATION_LABELS: Record<Duration, string> = {
  1: '1 Month',
  3: '3 Months',
  6: '6 Months',
};

/** Savings percentage shown as badge on longer plans */
export const DURATION_SAVINGS: Partial<Record<Duration, string>> = {
  3: 'Save 13%',
  6: 'Save 17%',
};

export interface FAQItem {
  question: string;
  answer: string;
}

export const PRICING_FAQ: FAQItem[] = [
  {
    question: "Is there a free trial available?",
    answer: "Yes! You can explore our basic market tools and public tickers for free. However, our premium institutional-grade signals and deep-dive analytics require an active subscription to any of our plans."
  },
  {
    question: "Can I upgrade or cancel my plan anytime?",
    answer: "Absolutely. You can upgrade to a higher tier at any time to unlock more features. Subscriptions can be managed or cancelled directly from your user dashboard."
  },
  {
    question: "Are the trading signals delivered in real-time?",
    answer: "Yes, all our Diamond and Gold plan signals are generated by our proprietary AI models and institutional algorithms, delivered instantly via your dashboard and alerts."
  },
  {
    question: "What payment methods do you accept?",
    answer: "We support a wide range of secure payment methods through Razorpay, including all major Credit/Debit cards, UPI, and Net Banking."
  },
  {
    question: "Do you offer professional portfolio management?",
    answer: "Our Diamond plan includes advanced portfolio tracking tools. For personalized institutional-level management, please contact our research team directly via the Contacts page."
  }
];
